Form/Type/Base/UserType.php
<?php

namespace Smirik\AdminBundle\Form\Type\Base;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('username')
            ->add('email')
            ->add('enabled')
            ->add('groups')
            ->add('plainPassword')
        ;
    }

    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(
            array(
                'data_class' => 'FOS\UserBundle\Propel\User'
            )
        );
    }

    public function getName()
    {
        return 'User';
    }

}

Form/Type/UserType.php
<?php

namespace Smirik\AdminBundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('username')
            ->add('email')
            ->add('enabled')
            ->add('groups', 'model', array(
                  'class'    => 'FOS\UserBundle\Propel\Group',
                  'multiple' => true,
                  'required' => false,
            ))
            ->add('plainPassword', 'text', array(
                'required' => false,
            ))
        ;
    }

    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(
            array(
                'data_class' => 'FOS\UserBundle\Propel\User'
            )
        );
    }

    public function getName()
    {
        return 'User';
    }

}

Controller/Base/AdminUserController.php
<?php

namespace Smirik\AdminBundle\Controller\Base;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;

use Smirik\PropelAdminBundle\Controller\AdminAbstractController as AbstractController;

class AdminUserController extends AbstractController
{
	
	public $layout = 'SmirikAdminBundle::layout.html.twig';
	public $name   = 'users';
	public $bundle = 'SmirikAdminBundle';

	public function getQuery()
	{
		return \Smirik\AdminBundle\Model\UserQuery::create();
	}
	
	public function getForm()
	{
		return new \Smirik\AdminBundle\Form\Type\UserType;
	}
	
	public function getObject()
	{
		return new \FOS\UserBundle\Propel\User;
	}

}

Resources/views/Admin/User/logs.html.twig
{% extends 'SmirikAdminBundle::layout.html.twig' %}

{% block title %}{{ 'User statistics'|trans }}{% endblock %}

{% block header %}
    <h1>{{ 'Logs'|trans }} <small>{{ user.profile.name }}</small></h1>
{% endblock %}

{% block content %}

<h3>{{ start.format('Y-m-d') }} &mdash; {{ stop.format('Y-m-d')}}</h3>

    <table class="table table-bordered table-striped">
        <thead>
        <tr>
            <th rowspan="2">{{ 'Id'|trans }}</th>
            <th rowspan="2">{{ 'Type'|trans }}</th>
            <th rowspan="2">{{ 'Name'|trans }}</th>
            <th rowspan="2">{{ 'Amount'|trans }}</th>
        </tr>
        </thead>
        <tr>
            <td>&mdash;</td>
            <td>{{ 'Homepage'|trans }}</td>
            <td>&mdash;</td>
            <td>{{ logs.homepage }}</td>
        </tr>
        <tr>
            <th colspan="4">{{ 'Courses'|trans }}</th>
        </tr>
        {% for course_log in logs.course_logs %}
            <tr>
                <td>{{ course_log.object.Id }}</td>
                <td>{{ 'Course'|trans }}</td>
                <td>{{ course_log.object.Title }}</td>
                <td>{{ course_log.num }}</td>
            </tr>
        {% endfor %}
        <tr>
            <th colspan="4">{{ 'Lessons'|trans }}</th>
        </tr>
        {% for lesson_log in logs.lesson_logs %}
            <tr>
                <td>{{ lesson_log.object.Id }}</td>
                <td>{{ 'Lesson'|trans }}</td>
                <td>{{ lesson_log.object.Title }}</td>
                <td>{{ lesson_log.num }}</td>
            </tr>
        {% endfor %}
        <tr>
            <th colspan="4">{{ 'Tasks'|trans }}</th>
        </tr>
        {% for task_log in logs.task_logs %}
            <tr>
                <td>{{ task_log.object.Id }}</td>
                <td>{{ 'Task'|trans }}</td>
                <td>{{ task_log.object.Title }} / {{ task_log.object.Lesson.Title }}</td>
                <td>{{ task_log.num }}</td>
            </tr>
        {% endfor %}
    </table>
    
    <div class="well">
        <a href="{{ path('admin_users_index') }}" class="btn">{{ 'Back'|trans }}</a>
    </div>

{% endblock %}

Resources/views/Admin/User/stat.html.twig
{% extends 'SmirikAdminBundle::layout.html.twig' %}

{% block title %}{{ 'User statistics'|trans }}{% endblock %}

{% block header %}
    <h1>{{ 'Statistics'|trans }} <small>{{ user.username }}</small></h1>
{% endblock %}

{% block content %}

  {% for user_course in users_courses %}
    <h3>{{ user_course.course.title }}</h3>
    <table class="table table-bordered table-striped">
      <thead>
        <tr>
          <th rowspan="2">#</th>
          <th rowspan="2">{{ 'Title'|trans }}</th>
          <th rowspan="2">{{ 'Started at'|trans }}</th>
          <th colspan="4">{{ 'Tasks'|trans }}</th>
          <th colspan="2">{{ 'Questions'|trans }}</th>
        </tr>
        <tr>
          <th>{{ 'Accepted'|trans }}</th>
          <th>{{ 'In progress'|trans }}</th>
          <th>{{ 'Draft'|trans }}</th>
          <th>{{ 'Mark'|trans }}</th>
          <th>{{ 'Written'|trans }}</th>
          <th>{{ 'Visible questions'|trans }}</th>
        </tr>
      </thead>
      {% for lesson in courses_lessons[user_course.courseId] %}
        <tr {% if lesson.UserLessons.first %}class="{{ lesson.UserLessons.first.BootstrapClass }}"{% endif %}>
          <td>{{ loop.index }}</td>
          <td>{{ lesson.title }}</td>
          <td>{% if lesson.UserLessons.first %}{{ lesson.UserLessons.first.startedAt('Y-m-d') }}{% endif %}</td>
          <td>{{ tasks_data[user_course.courseId]['tasks'][lesson.id]['accepted']}}</td>
          <td>{{ tasks_data[user_course.courseId]['tasks'][lesson.id]['in_progress']}}</td>
          <td>{{ tasks_data[user_course.courseId]['tasks'][lesson.id]['draft']}}</td>
          <td>
            {% if tasks_data[user_course.courseId]['count'][lesson.id] == 0 %}
              —
            {% else %}
              {{ tasks_data[user_course.courseId]['marks'][lesson.id]/tasks_data[user_course.courseId]['count'][lesson.id] }}
            {% endif %}
          </td>
          <td>{{ questions_data[user_course.courseId]['questions'][lesson.id] }}</td>
          <td>{{ questions_data[user_course.courseId]['visible'][lesson.id] }}</td>
        </tr>
      {% endfor %}
    </table>
  {% endfor %}
  
  <h3>{{ 'Quizes'|trans }}</h3>
  <table class="table table-bordered table-striped">
    <thead>
      <tr>
        <th>#</th>
        <th>{{ 'Title'|trans }}</th>
        <th>{{ 'Correct answers'|trans }}</th>
        <th>{{ 'num_questions'|trans }}</th>
        <th>%</th>
        <th>{{ 'Date'|trans }}</th>
      </tr>
    </thead>
    {% for user_quiz in user_quizes %}
      <tr>
        <td>{{ loop.index }}</td>
        <td>{{ user_quiz.Quiz.title }}</td>
        <td>{{ user_quiz.numRightAnswers }}</td>
        <td>{{ user_quiz.Quiz.numQuestions }}</td>
        <td>{{ '%10.0f'|format(user_quiz.numRightAnswers / user_quiz.Quiz.numQuestions * 100) }}%</td>
        <td>{{ user_quiz.createdAt('Y-m-d H:i') }}</td>
      </tr>
    {% endfor %}
  </table>

{% endblock %}